### ISSUE TITLE
we could use a new members photo

### ISSUE THREAD

**Issue by leee** [columbiaspace/columbiaspace.github.io#1]
the current one is pretty bad in terms of quality.

**Comment by jakehlee** [comment]
Uhh ignore above reference, not sure why it's there.

**Comment by leee** [comment]
Blocked on Julia Di actually scheduling a photo event.

**Comment by JuliaDi** [comment]
Photo event will happen once we have team shirts/jackets - probably around February.

**Comment by leee** [comment]
In guess we can reasonably close this since it's in the agenda. Thanks @JuliaDi
