### ISSUE TITLE
Upgrade to Bootstrap 4

### ISSUE THREAD

**Issue by tigerlily-he** [columbiaspace/columbiaspace.github.io#117]
Stable version of Bootstrap 4 has been released since January 2018.

**Comment by jakehlee** [comment]
Is this as easy as swapping out the CDN link? Or are there trickier considerations?

**Comment by tigerlily-he** [comment]
It's trickier. I tried swapping CDN link (actually we don't use CDN right now. We just have the whole Bootstrap source code) and lots of things are broken.

**Comment by jakebox** [comment]
Closing, because at this point Bootstrap 5 is out. Website seems fine to me.
