### ISSUE TITLE
News on individual mission pages not updated

### ISSUE THREAD

**Issue by jakehlee** [columbiaspace/columbiaspace.github.io#14]
Less of an issue, more of a TODO?

**Comment by leee** [comment]
We'll handle these on a mission by mission basis.

**Comment by jakehlee** [comment]
Is there really absolutely no way to have categorization? I shouldn't have to make 2 separate copies of each blog post

**Comment by leee** [comment]
oh, do you want each mission to have their own news as well? this is actually trivial to do in jekyll with the use of tags.

want me to deal?

**Comment by jakehlee** [comment]
Yeah, that would be great. The mission leaders mentioned they wanted News for their individual missions as well

**Comment by leee** [comment]
done! 5ac8d1844ae0d19d8854fc7bd3b836b38fc6accc
