### ISSUE TITLE
Google Calendar imbed looks really ugly

### ISSUE THREAD

**Issue by jakehlee** [columbiaspace/columbiaspace.github.io#16]
Like, 2003 ugly.
Someone on [reddit](https://www.reddit.com/r/google/comments/3vovx8/how_come_google_never_introduced_this_design_or/cxptt3h) suggested [Full Calendar](http://fullcalendar.io)?

**Comment by leee** [comment]
LGTM.

Check the source of http://fullcalendar.io/js/fullcalendar-2.5.0/demos/gcal.html for implementation.

**Comment by jakehlee** [comment]
Functional, issue is purely aesthetics. Low priority since content and functionality comes first.
