### ISSUE TITLE
We need a past missions page

### ISSUE THREAD

**Issue by jakehlee** [columbiaspace/columbiaspace.github.io#22]
Missions such as NASABIG aren't current, but we need to record that we at least participated.

**Comment by leee** [comment]
Is the intention to have a separate page linking to all previous missions or have a dropdown menu `<hr>`ed?

**Comment by jakehlee** [comment]
Either or, depends on how much we plan on keeping.

If we plan on keeping the entire mission page, the hr would work.

If we can just do a quick summary, a separate page with just mission name and summary would work.

I'm thinking the first option since its a lot less work?

**Comment by leee** [comment]
First is preferable, I think.

The latter causes problems with news separation.

**Comment by jakehlee** [comment]
Fixed by 452a892
