### ISSUE TITLE
Standardize Mission names

### ISSUE THREAD

**Issue by jakehlee** [columbiaspace/columbiaspace.github.io#24]
Is it MicroG? Micro-G? RASCAL? RASC-AL? Weather Balloons? High Altitude Balloons? Names are all over the place.

It should be:
Micro-G for the website, microg for file names
RASC-AL for the website, rascal for file names
Weather Balloons for the website, balloons for file names

Also plurality is weird.
Should be fixed along with #3

**Comment by leee** [comment]
This is related to #3.

Filenames should remain capital-agnostic, so we'll prefer lowercase.

Capitalization would therefore then be stylistic.

**Comment by jakehlee** [comment]
Note: using High Altitude Balloons instead of Weather Balloons
