### ISSUE TITLE
We need a 404 page

### ISSUE THREAD

**Issue by jakehlee** [columbiaspace/columbiaspace.github.io#26]

**Comment by jakehlee** [comment]
Let's have fun with this one, think of something creative

**Comment by leee** [comment]
bump @prichardsf

**Comment by prichardsf** [comment]
Thanks for your help, I finally figured out how to upload images

I tried to make a Star Wars joke, but if you want something else let me know
https://www.youtube.com/watch?v=532j-186xEQ
