### ISSUE TITLE
We need a detailed README

### ISSUE THREAD

**Issue by jakehlee** [columbiaspace/columbiaspace.github.io#30]

**Comment by leee** [comment]
What should it cover?

**Comment by jakehlee** [comment]
Dev roles, technical explanation (jekyll, whatever), showcase some fantastic stuff we have going on

**Comment by JuliaDi** [comment]
Probably also wise to explain how to make posts and standardize their formats (if they need standardization).

**Comment by jakehlee** [comment]
Progress made by 1bf59d8b9e05b5d4f0d4caedeaf1dc59128139b1
