### ISSUE TITLE
some missions have multiple directors

### ISSUE THREAD

**Issue by leee** [columbiaspace/columbiaspace.github.io#31]
this needs to be rectified by teaching liquid how to deal with additional directors.

**Comment by jakehlee** [comment]
Website reverted as of fb9ff64be70a5088a3005def17575258f0534cf0 , fixes incoming within 6 hours.

**Comment by jakehlee** [comment]
Fixed by a5d37b23d0fa65ba9fae217af34d99b57fcc06d7
