### ISSUE TITLE
mission-microg needs jumbo and media disabled

### ISSUE THREAD

**Issue by leee** [columbiaspace/columbiaspace.github.io#32]
ask Kristina Andreyeva and/or Tamas Sarvary for materials.

**Comment by leee** [comment]
Media disabled, still needs jumbo.

**Comment by leee** [comment]
blocked on mission directors sending materials.

**Comment by jakehlee** [comment]
Weird, the jumbo image works on my end when I jekyll-serve but not on the website itself. Issue is server side?

**Comment by jakehlee** [comment]
Yep, http://columbiaspace.org/assets/media/img/microg/cover.jpg 404s when it shouldn't.
