### ISSUE TITLE
about: the subscribe needs to be resized to include the full length of the example email address

### ISSUE THREAD

**Issue by leee** [columbiaspace/columbiaspace.github.io#34]

**Comment by jakehlee** [comment]
Can't reproduce on my end:
<img width="559" alt="screen shot 2016-01-06 at 11 03 24 pm" src="https://cloud.githubusercontent.com/assets/1744665/12144243/b82c5cc2-b4c9-11e5-91c7-4ccda5a2e159.png">

**Comment by leee** [comment]
![but-i-can](https://cloud.githubusercontent.com/assets/963328/12153240/e333830c-b486-11e5-948d-240a60d64177.png)

**Comment by jakehlee** [comment]
Can't deal with bootstrap right now, will deal with later
