### ISSUE TITLE
Either a image-loading indicator or a low-res to high-res solution

### ISSUE THREAD

**Issue by jakehlee** [columbiaspace/columbiaspace.github.io#36]
Because jumbo-images serve a very important role in our website's specific design, we need a way to deal with users with slower internet speeds. We need to indicate that content is incoming. Either:
1. Do a loading bar thing for the image
2. Load a low-res first then load the high-res
It's not critical, but we should research how to provide the best experience possible for all users.

**Comment by jakehlee** [comment]
Or make the server better. What server is this on right now anyways?

**Comment by leee** [comment]
Everything is hosted with github-pages.

The issue here isn't the "server", it's the fact that these photos are just absurdly huge. Resolutions include: lower resolution, making all clients obtain better networking, and we all know that won't happen.

**Comment by jakehlee** [comment]
Fixed by c5590b0be4966183e96a31385b60a50dbb356091
