### ISSUE TITLE
Automatic update of the copyright year

### ISSUE THREAD

**Issue by jakehlee** [columbiaspace/columbiaspace.github.io#49]
Referencing #48 , we shouldn't have to do this every year. Could be implemented using either jekyll/liquid or javascript.

**Comment by mikeumus** [comment]
Or [DocPad](https://github.com/docpad/docpad). At NewSpace NYC we're moving to DocPad and you can just rock `<%- (new Date()).getFullYear() %>`

See DocPad vs Jekyll: 
- https://www.quora.com/Is-DocPad-or-Jekyll-better-for-static-web-development

Basically depends on if you prefer working in a Ruby or Node ecosystem.
