### ISSUE TITLE
we need a favicon

### ISSUE THREAD

**Issue by leee** [columbiaspace/columbiaspace.github.io#5]
thankfully, we've already a logo to use

**Comment by jakehlee** [comment]
fixed, ec6d80582614389a19a1f2c1dd061493a3389fd7

**Comment by jakehlee** [comment]
fixed, ec6d80582614389a19a1f2c1dd061493a3389fd7

**Comment by leee** [comment]
HTML imports, what is it

**Comment by jakehlee** [comment]
FINE

**Comment by jakehlee** [comment]
HTML imports were removed by 087d1835cf2b608a49466123473edce23ac0f5b6 and 94fa611af440df781301ac04491ea0bb3c030f74 .

Head compartmentalization refers to issue #7
