### ISSUE TITLE
news articles are too constrained in terms of width

### ISSUE THREAD

**Issue by leee** [columbiaspace/columbiaspace.github.io#51]
just a visual/aesthetic thing, although now that I reconsider it...

it's an
````
               ~ * ~ * ~ A E S T H E T I C   T H I N G ~ * ~ * ~
````

**Comment by jakehlee** [comment]
The entire news page needs to change - twitter should be an expandable sidebar, and the news articles should collapse or paginate. The page is way too long right now.

I'm thinking of doing the "Read More..." implementation for shortening up the page.

**Comment by leee** [comment]
No need for an expandable sidebar I think - what could be better is for the pages to be a bit wider.
